# Generated by Django 4.0.6 on 2022-08-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yearly_intrest_rate', models.FloatField()),
                ('minimum_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('ifsc', models.CharField(max_length=16)),
                ('balance', models.FloatField()),
                ('holder_name', models.CharField(max_length=200)),
                ('holder_email', models.CharField(max_length=200)),
                ('holder_phone', models.CharField(max_length=15)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accounttype')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
