# Generated by Django 4.0.6 on 2022-08-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cardtype_alter_accounttype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='overdue_monthly_intrest_rate',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
