# Generated by Django 4.0.6 on 2022-08-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cardtype_overdue_monthly_intrest_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardtype',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('card_holder_name', models.CharField(max_length=200)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('current_month_usage', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cardtype')),
            ],
        ),
    ]
