# Generated by Django 4.0.6 on 2022-08-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cardtype_options_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(default=123, max_length=3),
            preserve_default=False,
        ),
    ]
